using System.Collections.Generic;
using System.Text;

namespace netcore.Untity
{
    public static class TemplateGenerator
    {
        public static string GetHTMLString()
        {
            var teacher = Item.GetAllTeacher();
            var sb = new StringBuilder();
            //string w = 'thunwa';
            //วิธีนำค่าตัวแปลไปใส่ในฟอร์มสตริง // '+$'{ตัวแปร}'+@'   //
            sb.Append(@"<div>
    <p style='text-align:right;'>แบบCS1</p>
    <p style='margin-top:0pt; margin-bottom:0pt; text-align:center; font-size:16pt;'><span style='height:0pt; text-align:left; display:block; position:absolute; z-index:0;'>
        
      </span><strong><span style='font-family:'TH SarabunPSK';'>&nbsp;</span></strong><strong><span style='font-family:'TH SarabunPSK';'>แบบเสนอหัวข้องานวิจัย</span></strong><strong><span style='font-family:'TH SarabunPSK';'>ทางเทคโนโลยีสารสนเทศ</span></strong></p>


    <p style='margin-top:0pt; margin-bottom:0pt; text-align:center; font-size:16pt;'><strong><span style='font-family:'TH SarabunPSK';'>คณะวิทยาศาสตร์</span></strong><strong><span style='font-family:'TH SarabunPSK';'>&nbsp;</span></strong><strong><span style='font-family:'TH SarabunPSK';'>มหาวิทยาลัยราชภัฏจันทรเกษม</span></strong></p>
    <p style='margin-top:0pt; margin-bottom:0pt; font-size:16pt;'><span style='font-family:'TH SarabunPSK';'>&nbsp;</span></p>
    <p style='margin-top:0pt; margin-bottom:0pt; font-size:16pt;'><span style='font-family:'TH SarabunPSK';'>1.&nbsp;</span><span style='font-family:'TH SarabunPSK';'>รหัสประจำตัว</span><span style='font-family:'TH SarabunPSK';'>&nbsp;</span><input style='border:none;font-size:18px;width:100px;' type='text' name='' value='5911501335'>
<span style='font-family:'TH SarabunPSK';'>&nbsp; &nbsp;</span><span style='font-family:'TH SarabunPSK';'>&nbsp;</span><span style='font-family:'TH SarabunPSK';'>ชื่อ</span><span style='font-family:'TH SarabunPSK';'>-</span><span style='font-family:'TH SarabunPSK';'>สกุล</span><span style='font-family:'TH SarabunPSK';'>&nbsp;</span><input style='border:none;font-size:18px;width:200px;' type='text' name='' value='ธันวา เม๊าะหะมะ '>
</p>
    <p style='margin-top:0pt; margin-bottom:0pt; font-size:16pt;'><span style='font-family:'TH SarabunPSK';'>&nbsp;</span></p>
    <p style='margin-top:0pt; margin-bottom:0pt; font-size:16pt;'><span style='font-family:'TH SarabunPSK';'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style='font-family:'TH SarabunPSK';'>นักศึกษา</span><span style='width:24.66pt; display:inline-block;'>&nbsp;</span><strong><span style='font-family:Webdings; font-size:10pt;'></span></strong><strong><span style='font-family:'TH SarabunPSK'; font-size:10pt;'>&nbsp;</span></strong><span style='font-family:'TH SarabunPSK';'>ภาคใ</span><span style='font-family:'TH SarabunPSK';'>นเวลา</span><span style='font-family:'TH SarabunPSK';'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style='font-family:'TH SarabunPSK';'>ชั้นปี</span><span style='font-family:'TH SarabunPSK';'>&nbsp;</span><span style='font-family:'TH SarabunPSK';'>4</span><span style='font-family:'TH SarabunPSK';'>&nbsp;</span><span style='font-family:'TH SarabunPSK';'>หมู่เรียน</span><span style='font-family:'TH SarabunPSK';'>&nbsp;</span><span style='font-family:'TH SarabunPSK';'>วทบ</span><span style='font-family:'TH SarabunPSK';'>.591</span><span style='font-family:'TH SarabunPSK';'>(4)/2</span><span style='width:9.64pt; display:inline-block;'>&nbsp;</span><span style='font-family:'TH SarabunPSK';'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</span></p>
    <p style='margin-top:0pt; margin-bottom:0pt; font-size:16pt;'><span style='font-family:'TH SarabunPSK';'>&nbsp;</span></p>
    <p style='margin-top:0pt; margin-bottom:0pt; font-size:16pt;'><span style='font-family:'TH SarabunPSK';'>2.&nbsp;</span><span style='font-family:'TH SarabunPSK';'>ชื่อหัวข้อที่นำเสนอ</span></p>
    <p style='margin-top:0pt;margin-left:70.9pt;margin-bottom:0pt;text-indent:-70.9pt;font-size: 16pt;'><span style='font-family:'TH SarabunPSK';'>&nbsp;&nbsp;&nbsp;&nbsp;</span><span style='font-family:'TH SarabunPSK';'>ภาษาไทย</span><span style='font-family:'TH SarabunPSK';'>&nbsp;</span><span style='width:16.74pt; text-indent:0pt; display:inline-block;'>&nbsp;</span><input style='border:none;font-size:18px;width:500px;' type='text' name='' value='เว็บแอพพลิเคชั่นระบบขายไก่สดออนไลน์'></p>
    <p style='margin-top:0pt; margin-left:70.9pt; margin-bottom:0pt; text-indent:-70.9pt; font-size:16pt;'><span style='font-family:'TH SarabunPSK';'>&nbsp;&nbsp;&nbsp;&nbsp;</span><span style='font-family:'TH SarabunPSK';'>ภาษาอังกฤษ</span><span style='font-family:'TH SarabunPSK';'>&nbsp;</span>&nbsp;<input style='border:none;font-size:18px;width:500px;' type='text' name='' value='The development of Online fresh Chiken Shop '></p>
    <p style='margin-top:0pt; margin-bottom:0pt; font-size:16pt;'><span style='font-family:'TH SarabunPSK';'>&nbsp;</span></p>
    <p style='margin-top:0pt; margin-bottom:0pt; font-size:16pt;'><span style='font-family:'TH SarabunPSK';'>3.&nbsp;</span><span style='font-family:'TH SarabunPSK';'>ความเป็นมาและความสำคัญของปัญหา</span></p>
    <p style='margin-top:0pt; margin-bottom:0pt; text-indent:35.3pt; font-size:16pt;'><span style='font-family:'TH SarabunPSK';'>ในปัจจุบันการขายสินค้าออนไลน์นั้นมีหลากหลายรูปแบบ</span><span style='font-family:'TH SarabunPSK';'>&nbsp;</span><span style='font-family:'TH SarabunPSK';'>เช่น</span><span style='font-family:'TH SarabunPSK';'>การให้บริการด้านการซื้ออาหารสำเร็จรูปหรือ</span><span style='font-family:'TH SarabunPSK';'>อุปกรณ์</span><span style='font-family:'TH SarabunPSK';'>เครื่องใช้ต่างๆ</span><span style='font-family:'TH SarabunPSK';'>&nbsp;</span><span style='font-family:'TH SarabunPSK';'>แต่ที่ยังมีไม่มากนักนั้นคือร้านขายอาหารที่เป็นวัตถุดิบอาหาร</span><span style='font-family:'TH SarabunPSK';'>ประเภท</span><span style='font-family:'TH SarabunPSK';'>ของสด</span><span style='font-family:'TH SarabunPSK';'>ในรูปแบบออนไลน์</span><span style='font-family:'TH SarabunPSK';'>&nbsp;</span><span style='font-family:'TH SarabunPSK';'>เนื่องจากปัจจุบันผู้วิจัยได้ทำการค้าขายเกี่ยวกับสินค้าวัตถุดิบที่เป็นไก่สดจากตลาดอยู่แล้วทำให้เล็งเห็นปัญหาในการสั่งซื้อวัตถุดิบของลูกค้าที่โทรเข้ามาสั่งซื้อจากภายนอก</span><span style='font-family:'TH SarabunPSK';'>&nbsp;</span><span style='font-family:'TH SarabunPSK';'>และการจดบันทึกข้อมูลการสั่งซื้อนั้นยังเป็นรูปแบบเอกสารที่เป็นกระดาษทำให้เกิดปัญหาเวลาต้องการเรียกดูข้อมูลอย่างเร่งด่วนและไม่สะดวกต่อการจัดเก็บข้อมูลบัญชี</span><span style='font-family:'TH SarabunPSK';'>&nbsp;</span></p>
    <p style='margin-top:0pt; margin-bottom:0pt; text-indent:35.3pt; font-size:16pt;'><span style='font-family:'TH SarabunPSK';'>เนื่องจาก</span><span style='font-family:'TH SarabunPSK';'>ในยุคปัจจุบันเทคโนโลยีเริ่มมีการเจริญเติบโตไม่ว่าจะเป็นโทรศัพท์สมาร์</span><span style='font-family:'TH SarabunPSK';'>ท</span><span style='font-family:'TH SarabunPSK';'>โฟ</span><span style='font-family:'TH SarabunPSK';'>น</span><span style='font-family:'TH SarabunPSK';'>&nbsp;</span><span style='font-family:'TH SarabunPSK';'>แท็บเล็ต</span><span style='font-family:'TH SarabunPSK';'>&nbsp;</span><span style='font-family:'TH SarabunPSK';'>อินเทอร์เน็ต</span><span style='font-family:'TH SarabunPSK';'>&nbsp;</span><span style='font-family:'TH SarabunPSK';'>โซเชียลมีเดีย</span><span style='font-family:'TH SarabunPSK';'>&nbsp;</span><span style='font-family:'TH SarabunPSK';'>ฯลฯ</span><span style='font-family:'TH SarabunPSK';'>&nbsp;</span><span style='font-family:'TH SarabunPSK';'>สิ่งเหล่านี้ถูกนำมาช่วยในธุรกิจ</span><span style='font-family:'TH SarabunPSK';'>&nbsp;</span><span style='font-family:'TH SarabunPSK';'>และเริ่มมีบทบาท</span><span style='font-family:'TH SarabunPSK';'>&nbsp;</span><span style='font-family:'TH SarabunPSK';'>ในชีวิตประจำวันของคนเรามากขึ้น</span><span style='font-family:'TH SarabunPSK';'>&nbsp;</span><span style='font-family:'TH SarabunPSK';'>ทำให้ความต้องการของคนเรานั้นต้องการความสะดวกสบาย</span><span style='font-family:'TH SarabunPSK';'>&nbsp;</span><span style='font-family:'TH SarabunPSK';'>ความรวดเร็ว</span><span style='font-family:'TH SarabunPSK';'>&nbsp;</span><span style='font-family:'TH SarabunPSK';'>และความทันสมัย</span><span style='font-family:'TH SarabunPSK';'>&nbsp;(</span><span style='font-family:'TH SarabunPSK';'>วสันต์ฤกษ์องค์ดี</span><span style='font-family:'TH SarabunPSK';'>,&nbsp;</span><span style='font-family:'TH SarabunPSK';'>2556)</span>
      <br><span style='font-family:'TH SarabunPSK';'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style='font-family:'TH SarabunPSK';'>ผู้วิจัยจึงมีแนวคิดที่จะทำร้านขายไก่สดออนไลน์เพื่อพัฒนาและต่อยอดร้านขายไก่สดธรรมดาให้เป็นตลาดการค้าไก่สดออนไลน์เพื่ออำนวยความสะดวกสบายให้กับลูกค้าที่ต้องการสั่งซื้อไก่สดไปทำวัตถุดิบต่างๆ</span><span style='font-family:'TH SarabunPSK';'>&nbsp;</span><span style='font-family:'TH SarabunPSK';'>แถมยังช่วยประหยัดต้นทุนและเวลาในการสั่งซื้อวัตถุดิบ</span><span style='font-family:'TH SarabunPSK';'>&nbsp;</span><span style='font-family:'TH SarabunPSK';'>เพื่อให้ลูกค้าที่เข้ามาซื้อเกิดความสะดวกมากที่สุด</span><span style='font-family:'TH SarabunPSK';'>&nbsp;&nbsp;</span><span style='font-family:'TH SarabunPSK';'>ดังนั้นผู้วิจัยมีแนวคิดที่จะนำเทคโนโลยีเว็บเข้ามาช่วยจัดการระบบโดยการพัฒนาระบบการสั่งซื้อไก่สดออนไลน์ผ่านทางเว็บแอพพลิเคชั่นทั้ง</span><span style='font-family:'TH SarabunPSK';'>สมาร์</span><span style='font-family:'TH SarabunPSK';'>ทโฟน</span><span style='font-family:'TH SarabunPSK';'>&nbsp;</span><span style='font-family:'TH SarabunPSK';'>แท็บเล็ตและคอมพิวเตอร์โดยผู้ใช้สามารถเลือกดูรายการชนิดวัตถุดิบต่างๆ</span><span style='font-family:'TH SarabunPSK';'>&nbsp;</span><span style='font-family:'TH SarabunPSK';'>รวมทั้งสามารถบันทึกข้อมูลลูกค้าและเรียกใช้ข้อมูลได้</span><span style='font-family:'TH SarabunPSK';'>&nbsp;</span><span style='font-family:'TH SarabunPSK';'>อีกทั้งเพื่อให้มีการบริการลูกค้าที่มีประสิทธิภาพมากขึ้นและเข้าถึงกลุ่มลูกค้าเป้าหมายได้มากขึ้น</span><span style='font-family:'TH SarabunPSK';'>&nbsp;</span></p>
    <p style='margin-top:0pt; margin-bottom:0pt; text-indent:35.45pt; text-align:justify; font-size:16pt;'><span style='font-family:'TH SarabunPSK';'>&nbsp;</span></p>
    <p style='margin-top:0pt; margin-bottom:0pt; font-size:16pt;'><span style='font-family:'TH SarabunPSK';'>&nbsp;</span></p>
    <p style='margin-top:0pt; margin-bottom:0pt; font-size:16pt;'><span style='font-family:'TH SarabunPSK';'>&nbsp;</span></p>
    <p style='margin-top:0pt; margin-bottom:0pt; font-size:16pt;'><span style='font-family:'TH SarabunPSK';'>&nbsp;</span></p><p style='margin-top:0pt; margin-bottom:0pt; font-size:16pt;'><span style='font-family:'TH SarabunPSK';'><br></span></p><p style='margin-top:0pt; margin-bottom:0pt; font-size:16pt;'><span style='font-family:'TH SarabunPSK';'><br></span></p>
    <p style='margin-top:0pt; margin-bottom:0pt; font-size:16pt;'><span style='font-family:'TH SarabunPSK';'>4.</span><span style='font-family:'TH SarabunPSK';'>วัตถุประสงค์</span></p>
    <p style='margin-top:0pt; margin-left:70.9pt; margin-bottom:0pt; text-indent:-70.9pt; font-size:16pt;'><span style='font-family:'TH SarabunPSK';'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style='font-family:'TH SarabunPSK';'>4.1&nbsp;</span><span style='font-family:'TH SarabunPSK';'>เพื่อวิเคราะห์และออกแบบระบบร้านขายไก่สดผ่านระบบออนไลน์</span></p>
    <p style='margin-top:0pt; margin-left:70.9pt; margin-bottom:0pt; text-indent:-70.9pt; font-size:16pt;'><span style='font-family:'TH SarabunPSK';'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style='font-family:'TH SarabunPSK';'>4.2&nbsp;</span><span style='font-family:'TH SarabunPSK';'>เพื่อสร้างระบบที่สามารถจัดการฐานข้อมูลการขายสินค้าที่เกี่ยวข้องกับระบบร้านขายไก่ออนไลน์</span></p>
    <p style='margin-top:0pt; margin-bottom:0pt; font-size:16pt;'><span style='font-family:'TH SarabunPSK';'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style='font-family:'TH SarabunPSK';'>4.3&nbsp;</span><span style='font-family:'TH SarabunPSK';'>เพื่ออำนวยความสะดวกในการสั่งซื้อสินค้าให้แก่ลูกค้า</span></p>
    <p style='margin-top:0pt; margin-bottom:0pt; font-size:16pt;'><span style='font-family:'TH SarabunPSK';'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style='font-family:'TH SarabunPSK';'>4.4&nbsp;</span><span style='font-family:'TH SarabunPSK';'>เพื่อศึกษาและเข้าใจถึงระบบขายสินค้าออนไลน์</span></p>
    <p style='margin-top:0pt; margin-bottom:0pt; font-size:16pt;'><span style='font-family:'TH SarabunPSK';'>&nbsp;</span></p>
    <p style='margin-top:0pt; margin-bottom:0pt; font-size:16pt;'><span style='font-family:'TH SarabunPSK';'>5.&nbsp;</span><span style='font-family:'TH SarabunPSK';'>หลักการ</span><span style='font-family:'TH SarabunPSK';'>&nbsp;</span><span style='font-family:'TH SarabunPSK';'>ทฤษฎี</span><span style='font-family:'TH SarabunPSK';'>&nbsp;&nbsp;</span><span style='font-family:'TH SarabunPSK';'>เหตุผล</span></p>
    <p style='margin-top:0pt; margin-bottom:0pt; text-indent:35.45pt; font-size:16pt;'><span style='font-family:'TH SarabunPSK';'>ผู้วิจัยได้ทำการศึกษาและวิเคราะห์ปัญหาในการทำระบบด้วยการนำ</span><span style='font-family:'TH SarabunPSK';'>ทฤษฎีวงจรการพัฒนาระบ</span><span style='font-family:'TH SarabunPSK';'>บ</span><span style='font-family:'TH SarabunPSK';'>(</span><span style='font-family:'TH SarabunPSK';'>Systems</span><span style='font-family:'TH SarabunPSK';'>&nbsp;</span><span style='font-family:'TH SarabunPSK';'>Development Life Cycle : SDLC)</span><span style='font-family:'TH SarabunPSK';'>มาใช้ในการออกแบบและพัฒนาระบบและพัฒนาเว็บไซต์ด้วยภาษา</span><span style='font-family:'TH SarabunPSK';'>&nbsp;</span><span style='font-family:'TH SarabunPSK';'>PHP,HTML,JAVASCLIP,CSS&nbsp;</span><span style='font-family:'TH SarabunPSK';'>ร่วมกับฐานข้อมูล</span><span style='font-family:'TH SarabunPSK';'>&nbsp;</span><span style='font-family:'TH SarabunPSK';'>MySQL&nbsp;</span><span style='font-family:'TH SarabunPSK';'>นอกจากนี้ได้ใช้โปรแกรม</span><span style='font-family:'TH SarabunPSK';'>ATOM&nbsp;</span><span style='font-family:'TH SarabunPSK';'>เป็น</span><span style='font-family:'TH SarabunPSK';'>&nbsp;</span><span style='font-family:'TH SarabunPSK';'>textEditor</span><span style='font-family:'TH SarabunPSK';'>&nbsp;</span><span style='font-family:'TH SarabunPSK';'>ในการเขียนเพื่อให้ได้ระบบที่มีประสิทธิภาพและสวยงาม</span></p>
    <p style='margin-top:0pt; margin-bottom:0pt; font-size:16pt;'><span style='font-family:'TH SarabunPSK';'>&nbsp;</span></p>
    <table cellpadding='0' cellspacing='0' style='width:524.6pt; margin-right:9pt; margin-left:9pt; border:0.75pt solid #000000; border-collapse:collapse; float:left;'>
      
    </table>
    <p style='margin-top:0pt; margin-bottom:0pt; font-size:16pt;'><span style='font-family:'TH SarabunPSK';'>6.&nbsp;</span><span style='font-family:'TH SarabunPSK';'>ระยะเวลาดำเนินการ</span></p>
<img style='float: center; margin: 0px 0px 15px 15px;' src='http://www.projectengineer.net/wp-content/uploads/2018/09/gantt-chart-toms-planner.png' width='100%' height='400'>
    <p style='margin-top:0pt; margin-bottom:0pt; font-size:16pt;'><span style='font-family:'TH SarabunPSK';'>&nbsp;</span></p>
    <p style='margin-top:0pt; margin-bottom:0pt; font-size:16pt;'><span style='font-family:'TH SarabunPSK';'>7.&nbsp;</span><span style='font-family:'TH SarabunPSK';'>แผนการดำเนินงาน</span><span style='font-family:'TH SarabunPSK';'>&nbsp;</span><span style='font-family:'TH SarabunPSK';'>ขอบเขตการศึกษา</span></p>
    <p style='margin-top:0pt; margin-bottom:0pt; font-size:16pt;'><span style='font-family:'TH SarabunPSK';'>&nbsp;&nbsp;&nbsp;&nbsp;</span><span style='font-family:'TH SarabunPSK';'>7.1&nbsp;</span><span style='font-family:'TH SarabunPSK';'>แผนการดำเนินงาน</span><span style='font-family:'TH SarabunPSK';'>&nbsp;</span></p>
    <p style='margin-top:0pt; margin-bottom:0pt; text-align:justify; font-size:16pt;'><span style='font-family:'TH SarabunPSK';'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style='font-family:'TH SarabunPSK';'>&nbsp;</span><span style='font-family:'TH SarabunPSK';'>&nbsp;7.1.1&nbsp;</span><span style='font-family:'TH SarabunPSK';'>วางแผนปัญหาและศึกษาข้อมูลการทำร้านขายสินค้าออนไลน์</span><span style='font-family:'TH SarabunPSK';'>&nbsp;</span></p>
    <p style='margin-top:0pt; margin-bottom:0pt; text-align:justify; font-size:16pt;'><span style='font-family:'TH SarabunPSK';'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style='font-family:'TH SarabunPSK';'>&nbsp;</span><span style='font-family:'TH SarabunPSK';'>7.1.2&nbsp;</span><span style='font-family:'TH SarabunPSK';'>วิเคราะห์ข้อมูล</span><span style='font-family:'TH SarabunPSK';'>&nbsp;</span><span style='font-family:'TH SarabunPSK';'>และจัดทำวงจรพัฒนาระบบ</span><span style='font-family:'TH SarabunPSK';'>&nbsp;</span><span style='font-family:'TH SarabunPSK';'>SDLC</span></p>
    <p style='margin-top:0pt; margin-bottom:0pt; text-indent:35.45pt; text-align:justify; font-size:16pt;'><span style='font-family:'TH SarabunPSK';'>7.1.3</span><span style='font-family:'TH SarabunPSK';'>&nbsp;</span><span style='font-family:'TH SarabunPSK';'>สรุปปัญหาและเริ่มออกแบบระบบ</span></p>
    <p style='margin-top:0pt; margin-bottom:0pt; text-indent:35.45pt; text-align:justify; font-size:16pt;'><span style='font-family:'TH SarabunPSK';'>7.1.4&nbsp;</span><span style='font-family:'TH SarabunPSK';'>พัฒนาเว็บแอพพลิเคชั่นด้วยโปรแกรม</span><span style='font-family:'TH SarabunPSK';'>&nbsp;</span><span style='font-family:'TH SarabunPSK';'>sublime text3</span></p>
    <p style='margin-top:0pt; margin-bottom:0pt; text-align:justify; font-size:16pt;'><span style='font-family:'TH SarabunPSK';'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style='font-family:'TH SarabunPSK';'>&nbsp;</span><span style='font-family:'TH SarabunPSK';'>7.1.5&nbsp;</span><span style='font-family:'TH SarabunPSK';'>ประเมินความพึงพอใจของผู้ใช้งาน</span></p>
    <p style='margin-top:0pt; margin-bottom:0pt; text-align:justify; font-size:16pt;'><span style='font-family:'TH SarabunPSK';'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style='font-family:'TH SarabunPSK';'>7.1.6&nbsp;</span><span style='font-family:'TH SarabunPSK';'>จัดทำเอกสารคู่มือประกอบรูปเล่มวิจัยให้สมบูรณ์</span></p>
    <p style='margin-top:0pt; margin-bottom:0pt; font-size:16pt;'><span style='font-family:'TH SarabunPSK';'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style='font-family:'TH SarabunPSK';'>7.2&nbsp;</span><span style='font-family:'TH SarabunPSK';'>ขอบเขตการศึกษา</span><span style='font-family:'TH SarabunPSK';'>&nbsp;</span></p>
    <p style='margin-top:0pt; margin-bottom:0pt; text-align:justify; font-size:16pt;'><span style='font-family:'TH SarabunPSK';'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style='font-family:'TH SarabunPSK';'>7.2.1&nbsp;</span><span style='font-family:'TH SarabunPSK';'>ระบบสามารถ</span><span style='font-family:'TH SarabunPSK';'>&nbsp;</span><span style='font-family:'TH SarabunPSK';'>สั่งซื้อวัตถุดิบชิ้นส่วนไก่สดได้</span></p>
    <p style='margin-top:0pt; margin-bottom:0pt; text-indent:35.45pt; text-align:justify; font-size:16pt;'><span style='font-family:'TH SarabunPSK';'>7.2.2&nbsp;</span><span style='font-family:'TH SarabunPSK';'>ระบบสามารถคิดเงินได้</span></p>
    <p style='margin-top:0pt; margin-bottom:0pt; text-indent:35.45pt; text-align:justify; font-size:16pt;'><span style='font-family:'TH SarabunPSK';'>7.2.3&nbsp;</span><span style='font-family:'TH SarabunPSK';'>เจ้าของระบบสามารถดูรายการที่ลูกค้าสั่งซื้อได้</span></p>
    <p style='margin-top:0pt; margin-bottom:0pt; text-indent:35.45pt; text-align:justify; font-size:16pt;'><span style='font-family:'TH SarabunPSK';'>7.2.4&nbsp;</span><span style='font-family:'TH SarabunPSK';'>เจ้าของร้านสามารถเพิ่ม</span><span style='font-family:'TH SarabunPSK';'>/</span><span style='font-family:'TH SarabunPSK';'>ลบ</span><span style='font-family:'TH SarabunPSK';'>/</span><span style='font-family:'TH SarabunPSK';'>แก้ไข</span><span style='font-family:'TH SarabunPSK';'>&nbsp;</span><span style='font-family:'TH SarabunPSK';'>รายการวัตถุดิบได้</span></p>
    <p style='margin-top:0pt; margin-bottom:0pt; text-indent:35.45pt; text-align:justify; font-size:16pt;'><span style='font-family:'TH SarabunPSK';'>&nbsp;&nbsp;</span><span style='font-family:'TH SarabunPSK';'>&nbsp;</span></p>
    <p style='margin-top:0pt; margin-bottom:0pt; font-size:16pt;'><span style='font-family:'TH SarabunPSK';'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style='font-family:'TH SarabunPSK';'>7.3&nbsp;</span><span style='font-family:'TH SarabunPSK';'>ฮาร์ดแวร์</span><span style='font-family:'TH SarabunPSK';'>&nbsp;(</span><span style='font-family:'TH SarabunPSK';'>Hardware)</span><span style='font-family:'TH SarabunPSK';'>&nbsp;</span><span style='font-family:'TH SarabunPSK';'>ที่ใช้</span></p>
    <p style='margin-top:0pt; margin-bottom:0pt; font-size:16pt; background-color:#ffffff;'><span style='font-family:'TH SarabunPSK';'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style='font-family:'TH SarabunPSK';'>7.3.1&nbsp;</span><span style='font-family:'TH SarabunPSK'; color:#212121;'>CPU&nbsp;</span><span style='font-family:'TH SarabunPSK'; color:#212121;'>i</span><span style='font-family:'TH SarabunPSK'; color:#212121;'>5</span><span style='font-family:'TH SarabunPSK'; color:#212121;'>-</span><span style='font-family:'TH SarabunPSK'; color:#212121;'>8300</span><span style='font-family:'TH SarabunPSK'; color:#212121;'>H</span><span style='font-family:'TH SarabunPSK'; color:#212121;'>&nbsp;up to 3.8GHz,&nbsp;</span><span style='font-family:'TH SarabunPSK'; color:#212121;'>8</span><span style='font-family:'TH SarabunPSK'; color:#212121;'>MB cache</span></p>
    <p style='margin-top:0pt; margin-bottom:0pt; font-size:16pt; background-color:#ffffff;'><span style='font-family:'TH Sarabun New'; color:#212121;'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style='font-family:'TH Sarabun New'; color:#212121;'>&nbsp;</span><span style='font-family:'TH Sarabun New'; color:#212121;'>&nbsp;7.3.2 RAM 8GB DDR4</span></p>
    <p style='margin-top:0pt; margin-bottom:0pt; font-size:16pt; background-color:#ffffff;'><span style='font-family:'TH Sarabun New'; color:#212121;'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style='font-family:'TH Sarabun New'; color:#212121;'>7.3.3 HDD</span><span style='font-family:'TH Sarabun New'; color:#212121;'>&nbsp;&nbsp;</span><span style='font-family:'TH Sarabun New'; color:#212121;'>1TB&nbsp;</span></p>
    <p style='margin-top:0pt; margin-bottom:0pt; font-size:16pt;'><span style='font-family:'TH Sarabun New'; color:#212121;'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style='font-family:'TH Sarabun New'; color:#212121;'>7.3.4&nbsp;</span><span style='font-family:'TH SarabunPSK'; color:#212121;'>VGA</span><span style='font-family:'TH SarabunPSK'; color:#212121;'>&nbsp;GTX 1050</span><span style='font-family:'TH SarabunPSK'; color:#212121;'>&nbsp;TI</span><span style='font-family:'TH SarabunPSK'; color:#212121;'>&nbsp;4GB GDDR5</span></p>
    <p style='margin-top:0pt; margin-bottom:0pt; font-size:16pt;'><span style='width:36pt; display:inline-block;'>&nbsp;</span></p>
    <p style='margin-top:0pt; margin-bottom:0pt; font-size:16pt;'><span style='font-family:'TH SarabunPSK';'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style='font-family:'TH SarabunPSK';'>7.4&nbsp;</span><span style='font-family:'TH SarabunPSK';'>ซอฟท์แวร์</span><span style='font-family:'TH SarabunPSK';'>&nbsp;(</span><span style='font-family:'TH SarabunPSK';'>Software)&nbsp;</span><span style='font-family:'TH SarabunPSK';'>ที่ใช</span><span style='font-family:'TH SarabunPSK';'>้</span></p>
    <p style='margin-top:0pt; margin-bottom:0pt; text-indent:35.45pt; text-align:justify; font-size:16pt;'><span style='font-family:'TH SarabunPSK';'>&nbsp;</span><span style='font-family:'TH SarabunPSK';'>7.4.1 ATOM</span></p>
    <p style='margin-top:0pt; margin-bottom:0pt; text-indent:35.45pt; text-align:justify; font-size:16pt;'><span style='font-family:'TH SarabunPSK';'>&nbsp;</span><span style='font-family:'TH SarabunPSK';'>7.4.2&nbsp;</span><span style='font-family:'TH SarabunPSK';'>ภาษา</span><span style='font-family:'TH SarabunPSK';'>&nbsp;</span><span style='font-family:'TH SarabunPSK';'>PHP</span></p>
    <p style='margin-top:0pt; margin-bottom:0pt; text-align:justify; font-size:16pt;'><span style='font-family:'TH SarabunPSK';'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style='font-family:'TH SarabunPSK';'>&nbsp;&nbsp;&nbsp;</span><span style='font-family:'TH SarabunPSK';'>7.4.3 Adobe Photoshop CS6</span></p>
    <p style='margin-top:0pt; margin-bottom:0pt; text-align:justify; font-size:16pt;'><span style='font-family:'TH SarabunPSK';'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style='font-family:'TH SarabunPSK';'>&nbsp;&nbsp;&nbsp;</span><span style='font-family:'TH SarabunPSK';'>7.4.4 Googlechrome</span></p>
    <p style='margin-top:0pt; margin-bottom:0pt; text-align:justify; font-size:16pt;'><span style='font-family:'TH SarabunPSK';'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style='font-family:'TH SarabunPSK';'>7.4.5&nbsp;</span><span style='font-family:'TH SarabunPSK';'>Adobe Dreamweawer CS6</span></p>
    <p style='margin-top:0pt; margin-bottom:0pt; text-align:justify; font-size:16pt;'><span style='font-family:'TH SarabunPSK';'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span style='font-family:'TH SarabunPSK';'>7.4.6&nbsp;</span><span style='font-family:'TH SarabunPSK';'>FileZilla</span></p>
    <p style='margin-top:0pt; margin-bottom:0pt; text-indent:35.45pt; text-align:justify; font-size:16pt;'><span style='font-family:'TH SarabunPSK';'>&nbsp;</span><span style='font-family:'TH SarabunPSK';'>7.4.7&nbsp;</span><span style='font-family:'TH SarabunPSK';'>ฐานข้อมูล</span><span style='font-family:'TH SarabunPSK';'>&nbsp;</span><span style='font-family:'TH SarabunPSK';'>MySQLi</span></p>
    <p style='margin-top:0pt; margin-bottom:0pt; text-indent:35.45pt; text-align:justify; font-size:16pt;'><span style='font-family:'TH SarabunPSK';'>&nbsp;</span><span style='font-family:'TH SarabunPSK';'>7.4.8 Apache</span></p>
    <p style='margin-top:0pt; margin-bottom:0pt; text-indent:35.45pt; text-align:justify; font-size:16pt;'><span style='font-family:'TH SarabunPSK';'>&nbsp;</span></p><p style='margin-top:0pt; margin-bottom:0pt; text-indent:35.45pt; text-align:justify; font-size:16pt;'><span style='font-family:'TH SarabunPSK';'><br></span></p><p style='margin-top:0pt; margin-bottom:0pt; text-indent:35.45pt; text-align:justify; font-size:16pt;'><span style='font-family:'TH SarabunPSK';'><br></span></p><p style='margin-top:0pt; margin-bottom:0pt; text-indent:35.45pt; text-align:justify; font-size:16pt;'><span style='font-family:'TH SarabunPSK';'><br></span></p>
    <p style='margin-top:0pt; margin-bottom:0pt; font-size:16pt;'><span style='font-family:'TH SarabunPSK';'>8.&nbsp;</span><span style='font-family:'TH SarabunPSK';'>ประโยชน์ที่คาดว่าจะได้รับ</span></p>
    <p style='margin-top:0pt; margin-bottom:0pt; font-size:16pt;'><span style='font-family:'TH SarabunPSK';'>&nbsp;&nbsp;&nbsp;&nbsp;</span><span style='font-family:'TH SarabunPSK';'>8.1&nbsp;</span><span style='font-family:'TH SarabunPSK';'>เข้าใจและได้รับข้อมูลเกี่ยวกับการซื้อสินค้าออนไลน์</span></p>
    <p style='margin-top:0pt; margin-bottom:0pt; font-size:16pt;'><span style='font-family:'TH SarabunPSK';'>&nbsp;&nbsp;&nbsp;&nbsp;</span><span style='font-family:'TH SarabunPSK';'>8.2&nbsp;</span><span style='font-family:'TH SarabunPSK';'>ได้ผลการวิเคราะห์ระบบร้านขายไก่สดออนไลน์</span></p>
    <p style='margin-top:0pt; margin-bottom:0pt; font-size:16pt;'><span style='font-family:'TH SarabunPSK';'>&nbsp;&nbsp;&nbsp;&nbsp;</span><span style='font-family:'TH SarabunPSK';'>8.4&nbsp;</span><span style='font-family:'TH SarabunPSK';'>ได้ระบบร้านขายไก่สดออนไลน์ที่สามารถเชื่อมต่อกับฐานข้อมูลได้</span></p>
    <p style='margin-top:0pt; margin-bottom:0pt; font-size:16pt;'><span style='font-family:'TH SarabunPSK';'>&nbsp;&nbsp;&nbsp;&nbsp;</span><span style='font-family:'TH SarabunPSK';'>8.5&nbsp;</span><span style='font-family:'TH SarabunPSK';'>ช่วยลดปัญหาการซับซ้อนของข้อมูลและอำนวยความสะดวกให้กับผู้ใช้งาน</span></p>
    <p style='margin-top:0pt; margin-bottom:0pt; font-size:16pt;'><span style='font-family:'TH SarabunPSK';'>&nbsp;</span></p>
    <p style='margin-top:0pt; margin-bottom:0pt; font-size:16pt;'><span style='font-family:'TH SarabunPSK';'>&nbsp;</span></p>
    <p style='margin-top:0pt; margin-bottom:0pt; font-size:16pt;'><span style='font-family:'TH SarabunPSK';'>&nbsp;</span></p>
    <p style='margin-top:0pt; margin-bottom:0pt; font-size:16pt;'><span style='font-family:'TH SarabunPSK';'>&nbsp;</span></p>
    <p style='margin-top:0pt; margin-bottom:0pt; font-size:16pt;'><span style='font-family:'TH SarabunPSK';'>&nbsp;</span></p>
    <p style='margin-top:0pt; margin-bottom:0pt; font-size:16pt;'><span style='font-family:'TH SarabunPSK';'>&nbsp;</span></p><p style='margin-top:0pt; margin-bottom:0pt; font-size:16pt;'><br></p>
    <p style='margin-top:0pt; margin-bottom:0pt; font-size:16pt;'><span style='font-family:'TH SarabunPSK';'>&nbsp;</span></p>
    <p style='margin-top:0pt; margin-bottom:0pt; font-size:16pt;'><span style='font-family:'TH SarabunPSK';'>9</span><span style='font-family:'TH SarabunPSK';'>.&nbsp;</span><span style='font-family:'TH SarabunPSK';'>ความคิดเห็นของอาจารย์ที่ปรึกษา</span></p>
    <p style='margin-top:0pt; margin-bottom:0pt; font-size:16pt;'><span style='font-family:'TH SarabunPSK';'>..............................................................................................................................................</span></p>
    <p style='margin-top:0pt; margin-bottom:0pt; font-size:16pt;'><span style='font-family:'TH SarabunPSK';'>&nbsp;</span></p>
    <p style='margin-top:0pt; margin-bottom:0pt; font-size:16pt;'><span style='font-family:'TH SarabunPSK';'>&nbsp;</span></p>
    <p style='text-align:center;margin-top:0pt; margin-bottom:0pt; font-size:16pt;'><span style='width:36pt; display:inline-block;'>&nbsp;</span><span style='width:36pt; display:inline-block;'>&nbsp;</span><span style='width:36pt; display:inline-block;'>&nbsp;</span><span style='font-family:'TH SarabunPSK';'>ลงชื่อ</span><span style='font-family:'TH SarabunPSK';'>.....................................................</span><span style='font-family:'TH SarabunPSK';'>อาจารย์ที่ปรึกษา</span></p>
    <p style='text-align:center;margin-top:0pt;margin-bottom:0pt;font-size: 12pt;'><span style='width:108.94pt; display:inline-block;'></span><span style='font-family:'TH SarabunPSK';'>&nbsp; (</span>
<input style='border:none' type='text' name='' value='อาจารย์ ปภาดา นาวากาญจน์'>

      <span style='font-family:'TH SarabunPSK';'>&nbsp;)</span></p>
    <p style='margin-top:0pt; margin-bottom:0pt; font-size:16pt;'><span style='font-family:'TH SarabunPSK';'>&nbsp;</span></p>
    <p style='margin-top:0pt; margin-bottom:0pt; font-size:16pt;'><span style='font-family:'TH SarabunPSK';'>&nbsp;</span></p>
    <p style='margin-top:0pt; margin-bottom:0pt; font-size:16pt;'><span style='font-family:'TH SarabunPSK';'>11.&nbsp;</span><span style='font-family:'TH SarabunPSK';'>ความเห็นของประธานหลักสูตร</span></p>
    <p style='margin-top:0pt; margin-bottom:0pt; font-size:16pt;'><span style='font-family:'TH SarabunPSK';'>&nbsp;</span></p>
    <p style='text-align:center;margin-top:0pt; margin-bottom:0pt; font-size:16pt;'><span style='width:36pt; display:inline-block;'>&nbsp;</span><span style='width:36pt; display:inline-block;'>&nbsp;</span><strong><span style='font-family:Webdings; font-size:14pt;'></span></strong><strong><span style='font-family:'TH SarabunPSK';'>&nbsp;</span></strong><strong><span style='font-family:'TH SarabunPSK';'>&nbsp;</span></strong><span style='font-family:'TH SarabunPSK';'>อนุมัติ</span><span style='font-family:'TH SarabunPSK';'>&nbsp;&nbsp;&nbsp;</span><span style='width:30.88pt; display:inline-block;'>&nbsp;</span><span style='width:36pt; display:inline-block;'>&nbsp;</span><strong><span style='font-family:Webdings; font-size:14pt;'></span></strong><strong><span style='font-family:'TH SarabunPSK';'>&nbsp;</span></strong><strong><span style='font-family:'TH SarabunPSK';'>&nbsp;</span></strong><span style='font-family:'TH SarabunPSK';'>ไม่อนุมัติ</span></p>
    <h1 style='margin-top:0pt; margin-bottom:0pt; page-break-after:avoid; font-size:16pt;'><span style='font-family:'TH SarabunPSK'; font-weight:normal;'>&nbsp;</span></h1>
    <p style='margin-top:0pt; margin-bottom:0pt; font-size:12pt;'><span style='font-family:'Times New Roman';'>&nbsp;</span></p>
    <p style='margin-top:0pt; margin-bottom:0pt; font-size:12pt;'><span style='font-family:'Times New Roman';'>&nbsp;</span></p>
    <h1 style='text-align:center;margin-top:0pt; margin-bottom:0pt; page-break-after:avoid; font-size:16pt;'><span style='font-family:'TH SarabunPSK'; font-weight:normal;'>&nbsp;&nbsp;&nbsp;</span><span style='font-family:'TH SarabunPSK'; font-weight:normal;'>&nbsp;&nbsp;</span><span style='width:110pt; display:inline-block;'>&nbsp;</span><span style='font-family:'TH SarabunPSK'; font-weight:normal;'>&nbsp;&nbsp;&nbsp;&nbsp;</span><span style='font-family:'TH SarabunPSK'; font-weight:normal;'>ลงชื่อ</span><span style='font-family:'TH SarabunPSK';'>.....................................................</span>
<span style='font-family:'TH SarabunPSK'; font-weight:normal;'>ประธานหลักสูตร</span></h1>
    <p style='text-align:center;margin-top:0pt; margin-bottom:0pt; font-size:16pt;'><span style='width:28.35pt; display:inline-block;'>&nbsp;</span><span style='font-family:'TH SarabunPSK';'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </span><span style='font-family:'TH SarabunPSK';'>(</span>
      <input style='border:none' type='text' name='' value='อาจารย์ ปภาดา นาวากาญจน์'><span style='font-family:'TH SarabunPSK';'>&nbsp;)</span></p>
  </div>");
            
            return sb.ToString();
        }
    }
}